import type { AbilityDef, BossDef } from './types';
import { STORIES } from './stories';

export const BOSSES: BossDef[] = [
  {
    kind: 'boss',
    id: 'fenrir',
    name: 'فنرير',
    title: 'الذئب الذي كسر القيد',
    maxHp: 640,
    image: 'assets/starting-portraits/fenrir.png',
    bannerPosition: '50% 32%',
    abilityIds: ['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9'],
    phase2Rule: 'lowest-ratio-two',
    phase2Text:
      'في المرحلة الثانية، الهجمات ذات الهدف الواحد تختار عشوائيًا واحدًا من البطلين الحيين الأقل في نسبة الحياة الحالية إلى القصوى. عند تساوي النسب، يحدد ترتيب الخانات الثابت أيهما يدخل ضمن الاثنين. عند بقاء بطل واحد يُستهدف وحده. بقية الهجمات لا تتغير.',
    combatStyle:
      'ضغط جسدي: أنياب، مخالب، قفزة تتجاوز الصدّ، وزئير يضعف ضربات الفريق. السلاسل المكسورة تستعمل للحماية، واستعادة النفس تزيل الاحتراق.',
    story: STORIES.fenrir,
    starter: true,
  },
  {
    kind: 'boss',
    id: 'yorigumo',
    name: 'يوريغومو',
    title: 'ناسجة المرايا',
    maxHp: 720,
    image: 'assets/starting-portraits/yorigumo.png',
    bannerPosition: '50% 10%',
    abilityIds: ['Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6', 'Y7', 'Y8', 'Y9'],
    phase2Rule: 'poisoned',
    phase2Text:
      'في المرحلة الثانية، الهجمات ذات الهدف الواحد تختار عشوائيًا من الأبطال الأحياء المسمومين عند بداية الجولة. إن لم يوجد مسموم، تختار من كل الأحياء. بقية الهجمات لا تتغير.',
    combatStyle:
      'ضغط بالسم والتوقيت: خيوط تعطل قوة الهجوم، حواجز حرير ومرآة تعكس الأذى، وافتراس يقوى ضد المسموم. نسخ المرايا ممثلة بحماية وانعكاس، بلا استدعاء وحدات إضافية.',
    story: STORIES.yorigumo,
    starter: true,
  },
];

const SINGLE = 'بطل واحد محدد عند بداية الجولة وفق قاعدة المرحلة.';
const DOUBLE = 'بطلان مختلفان من أحياء بداية الجولة؛ إن لم يبق إلا واحد يُستهدف مرة واحدة.';
const ALL = 'كل الأبطال الأحياء عند بداية الجولة، مع تجاهل من مات قبل التنفيذ.';
const SELF = 'الزعيم نفسه.';

export const BOSS_ABILITIES: AbilityDef[] = [
  // ——— فنرير ———
  {
    id: 'F1',
    ownerId: 'fenrir',
    name: 'عضة الغضب',
    bossTarget: 'single',
    effects: [{ type: 'damage', target: 'bossTargets', amount: 19 }],
    targetText: SINGLE,
    displayText: 'اضرب بطلًا واحدًا بـ19.',
    vfxText: 'أثر عضة ووميض قصير على الهدف.',
    vfx: ['bite'],
    image: 'assets/fenrir-complete-pack/fenrir-F1.png',
  },
  {
    id: 'F2',
    ownerId: 'fenrir',
    name: 'مخلبان متقاطعان',
    bossTarget: 'double',
    effects: [{ type: 'damage', target: 'bossTargets', amount: 13 }],
    targetText: DOUBLE,
    displayText: 'اضرب بطلين مختلفين بـ13 لكل واحد. إن بقي بطل واحد، يُضرب مرة واحدة.',
    vfxText: 'أثرا مخلب على الهدفين المحددين في نفس اللحظة.',
    vfx: ['claw'],
    image: 'assets/fenrir-complete-pack/fenrir-F2.png',
  },
  {
    id: 'F3',
    ownerId: 'fenrir',
    name: 'قفزة فوق الترس',
    bossTarget: 'single',
    effects: [{ type: 'damage', target: 'bossTargets', amount: 17, piercing: true }],
    targetText: SINGLE,
    displayText: 'اضرب بطلًا واحدًا بـ17 متجاوزًا صدّه؛ يبقى الصدّ محفوظًا.',
    vfxText: 'أثر قفزة/مخلب ثاقب نحو الهدف؛ يبقى رمز صدّه ظاهرًا.',
    vfx: ['claw'],
    image: 'assets/fenrir-complete-pack/fenrir-F3.png',
  },
  {
    id: 'F4',
    ownerId: 'fenrir',
    name: 'رجّة الممر',
    bossTarget: 'all',
    effects: [{ type: 'damage', target: 'bossTargets', amount: 8 }],
    targetText: ALL,
    displayText: 'اضرب كل بطل حي بـ8.',
    vfxText: 'موجة أرضية خفيفة تتفرع للأهداف الحية.',
    vfx: ['quake'],
    image: 'assets/fenrir-complete-pack/fenrir-F4.png',
  },
  {
    id: 'F5',
    ownerId: 'fenrir',
    name: 'عواء الخيانة',
    bossTarget: 'all',
    effects: [
      { type: 'damage', target: 'bossTargets', amount: 4 },
      { type: 'weaken', target: 'bossTargets', amount: 6 },
    ],
    targetText: ALL,
    displayText: 'اضرب كل بطل حي بـ4، ثم أضعف الضربة المباشرة التالية لكل واحد بـ6.',
    vfxText: 'حلقة عواء ثم رموز إضعاف على الأهداف بعد الضرر.',
    vfx: ['howl', 'debuff'],
    image: 'assets/fenrir-complete-pack/fenrir-F5.png',
  },
  {
    id: 'F6',
    ownerId: 'fenrir',
    name: 'تحطيم الترس',
    bossTarget: 'single',
    effects: [
      { type: 'damage', target: 'bossTargets', amount: 23, bonus: { kind: 'ifTargetShielded', amount: 8 } },
    ],
    targetText: SINGLE,
    displayText: 'اضرب بطلًا واحدًا بـ23؛ أضف 8 إن كان عليه صدّ، ثم اطرح قيمة الصدّ كالمعتاد.',
    vfxText: 'اصطدام ثقيل بالهدف؛ أظهر المكافأة8 فقط عند وجود صدّ محسوب، ثم نتيجة الامتصاص الفعلية.',
    vfx: ['claw'],
    image: 'assets/fenrir-complete-pack/fenrir-F6.png',
  },
  {
    id: 'F7',
    ownerId: 'fenrir',
    name: 'حلقة السلسلة',
    bossTarget: 'self',
    effects: [{ type: 'shield', target: 'owner', amount: 26 }],
    targetText: SELF,
    displayText: 'اكتسب صدّ 26.',
    vfxText: 'حلقة سلاسل بسيطة حول الزعيم وقيمة صدّ26.',
    vfx: ['shield'],
    image: 'assets/fenrir-complete-pack/fenrir-F7.png',
  },
  {
    id: 'F8',
    ownerId: 'fenrir',
    name: 'نَفَس الحرية',
    bossTarget: 'self',
    effects: [
      { type: 'heal', target: 'owner', amount: 24 },
      { type: 'cleanse', target: 'owner', remove: ['burn', 'weaken'] },
    ],
    targetText: SELF,
    displayText: 'استعد 24 حياة، وأزل احتراقك وإضعاف هجومك القديم. لا تزل علامة الصيد أو كشف الثغرة.',
    vfxText: 'توهج استعادة نفس، رقم العلاج الفعلي وإزالة الاحتراق والإضعاف القديم فقط.',
    vfx: ['heal', 'cleanse'],
    image: 'assets/fenrir-complete-pack/fenrir-F8.png',
  },
  {
    id: 'F9',
    ownerId: 'fenrir',
    name: 'ناب يمزق الجرح',
    bossTarget: 'single',
    effects: [
      { type: 'damage', target: 'bossTargets', amount: 19 },
      { type: 'dot', target: 'bossTargets', status: 'bleed', amount: 3, ticks: 2 },
    ],
    targetText: SINGLE,
    displayText: 'اضرب بطلًا واحدًا بـ19، ثم ضع نزيف 3 × نهايتَي جولتين.',
    vfxText: 'أثر عضة ثم رمز نزيف ونبضاته في نهاية الجولة.',
    vfx: ['bite', 'bleed'],
    image: 'assets/fenrir-complete-pack/fenrir-F9.png',
  },
  // ——— يوريغومو ———
  {
    id: 'Y1',
    ownerId: 'yorigumo',
    name: 'إبرة الحرير',
    bossTarget: 'single',
    effects: [
      { type: 'damage', target: 'bossTargets', amount: 14 },
      { type: 'dot', target: 'bossTargets', status: 'poison', amount: 3, ticks: 2 },
    ],
    targetText: SINGLE,
    displayText: 'اضرب بطلًا واحدًا بـ14، ثم ضع سم 3 × نهايتَي جولتين.',
    vfxText: 'خيط/إبرة نحو الهدف ثم رمز سم.',
    vfx: ['thread', 'poison'],
    image: 'assets/yorigumo-complete-pack/yorigumo-Y1.png',
  },
  {
    id: 'Y2',
    ownerId: 'yorigumo',
    name: 'خيط على المعصم',
    bossTarget: 'single',
    effects: [
      { type: 'damage', target: 'bossTargets', amount: 19 },
      { type: 'weaken', target: 'bossTargets', amount: 5 },
    ],
    targetText: SINGLE,
    displayText: 'اضرب بطلًا واحدًا بـ19، ثم أضعف ضربته المباشرة التالية بـ5.',
    vfxText: 'خيط قصير على الهدف ثم إضعاف هجومه التالي.',
    vfx: ['thread', 'debuff'],
    image: 'assets/yorigumo-complete-pack/yorigumo-Y2.png',
  },
  {
    id: 'Y3',
    ownerId: 'yorigumo',
    name: 'عقدتان سامتان',
    bossTarget: 'double',
    effects: [
      { type: 'damage', target: 'bossTargets', amount: 10 },
      { type: 'dot', target: 'bossTargets', status: 'poison', amount: 3, ticks: 2 },
    ],
    targetText: DOUBLE,
    displayText: 'اضرب بطلين مختلفين بـ10 لكل واحد، وضع على كل منهما سم 3 × نهايتَي جولتين.',
    vfxText: 'خيطان نحو الهدفين ثم رمز سم لكل واحد.',
    vfx: ['thread', 'poison'],
    image: 'assets/yorigumo-complete-pack/yorigumo-Y3.png',
  },
  {
    id: 'Y4',
    ownerId: 'yorigumo',
    name: 'ضباب القصر',
    bossTarget: 'all',
    effects: [{ type: 'dot', target: 'bossTargets', status: 'poison', amount: 3, ticks: 2 }],
    targetText: ALL,
    displayText: 'ضع على كل بطل حي سم 3 × نهايتَي جولتين. لا ضرر مباشر.',
    vfxText: 'ضباب خفيف ورموز سم على الأهداف؛ لا رقم ضرر مباشر وهمي.',
    vfx: ['poison'],
    image: 'assets/yorigumo-complete-pack/yorigumo-Y4.png',
  },
  {
    id: 'Y5',
    ownerId: 'yorigumo',
    name: 'شرنقة الحرير',
    bossTarget: 'self',
    effects: [{ type: 'shield', target: 'owner', amount: 24 }],
    targetText: SELF,
    displayText: 'اكتسب صدّ 24.',
    vfxText: 'إطار شرنقة حرير وقيمة صدّ24.',
    vfx: ['shield'],
    image: 'assets/yorigumo-complete-pack/yorigumo-Y5.png',
  },
  {
    id: 'Y6',
    ownerId: 'yorigumo',
    name: 'خيط يستنزف النبض',
    bossTarget: 'single',
    effects: [{ type: 'damage', target: 'bossTargets', amount: 22, healOwnerOnHit: 12 }],
    targetText: SINGLE,
    displayText: 'اضرب بطلًا واحدًا بـ22. إذا وصل أي ضرر مباشر إلى حياته بعد الصدّ، استعد 12 حياة.',
    vfxText: 'خيط ضربة نحو الهدف؛ عند تحقق ضرر مباشر موجب فقط يعود ضوء نحو الزعيمة للعلاج12.',
    vfx: ['thread', 'heal'],
    image: 'assets/yorigumo-complete-pack/yorigumo-Y6.png',
  },
  {
    id: 'Y7',
    ownerId: 'yorigumo',
    name: 'وجه في المرآة',
    bossTarget: 'self',
    effects: [{ type: 'shield', target: 'owner', amount: 18, reflect: 8 }],
    targetText: SELF,
    displayText: 'اكتسب صدّ 18 مع انعكاس 8 على صاحب أول هجوم مباشر غير ثاقب يصيب الحاجز.',
    vfxText: 'لمعان مرآة حول الزعيمة إن قُبل الحاجز؛ ارتداد ضوء وضرر8 عند تحقق شرط الانعكاس لاحقًا فقط.',
    vfx: ['mirror'],
    image: 'assets/yorigumo-complete-pack/yorigumo-Y7.png',
  },
  {
    id: 'Y8',
    ownerId: 'yorigumo',
    name: 'رقصة الأرجل الثماني',
    bossTarget: 'all',
    effects: [{ type: 'damage', target: 'bossTargets', amount: 9 }],
    targetText: ALL,
    displayText: 'اضرب كل بطل حي بـ9.',
    vfxText: 'آثار ضربات قصيرة على كل الأهداف في نفس اللحظة.',
    vfx: ['claw'],
    image: 'assets/yorigumo-complete-pack/yorigumo-Y8.png',
  },
  {
    id: 'Y9',
    ownerId: 'yorigumo',
    name: 'ناب السم الناضج',
    bossTarget: 'single',
    effects: [
      { type: 'damage', target: 'bossTargets', amount: 27, bonus: { kind: 'ifTargetPoisoned', amount: 8 } },
    ],
    targetText: SINGLE,
    displayText: 'اضرب بطلًا واحدًا بـ27؛ أضف 8 إذا كان ما زال مسمومًا بعد التطهير الفوري لهذه الحركة.',
    vfxText: 'ناب/وميض سام على الهدف؛ إبراز مكافأة8 فقط إذا ظل مسمومًا بعد التطهير الفوري.',
    vfx: ['bite', 'poison'],
    image: 'assets/yorigumo-complete-pack/yorigumo-Y9.png',
  },
];
