import type { AbilityDef, HeroDef } from './types';
import { STORIES } from './stories';

const HERO_PRICE = 100;

export const HEROES: HeroDef[] = [
  {
    kind: 'hero',
    id: 'hayato',
    name: 'هاياتو',
    title: 'بوابة الحديد',
    role: 'warrior',
    maxHp: 120,
    levelImages: [
      'assets/starting-portraits/hayato.png',
      'assets/hayato-complete-pack/hayato-level-2.png',
      'assets/hayato-complete-pack/hayato-level-3.png',
      'assets/hayato-complete-pack/hayato-level-4.png',
      'assets/hayato-complete-pack/hayato-level-5.png',
    ],
    abilityIds: ['H1', 'H2', 'H3', 'H4'],
    story: STORIES.hayato,
    flavor:
      'درع كبير وكاتانا، وقصته مبنية على حماية الهاربين. لذلك ضرره محدود، وقيمته في توقيت الصدّ وحماية الرفاق.',
    starter: true,
    gemPrice: HERO_PRICE,
  },
  {
    kind: 'hero',
    id: 'nuba',
    name: 'نوبا',
    title: 'سيدة القيظ',
    role: 'mage',
    maxHp: 88,
    levelImages: [
      'assets/starting-portraits/nuba.png',
      'assets/nuba-complete-pack-gallery/nuba-level-2.png',
      'assets/nuba-complete-pack-gallery/nuba-level-3.png',
      'assets/nuba-complete-pack-gallery/nuba-level-4.png',
      'assets/nuba-complete-pack-gallery/nuba-level-5.png',
    ],
    abilityIds: ['N1', 'N2', 'N3', 'N4'],
    story: STORIES.nuba,
    flavor:
      'صورتها تجمع الوهج بين كفيها، وقصتها عن توجيه الحرارة وتبديد الضباب السحري. قدراتها احتراق محسوب وكسر للحواجز.',
    starter: true,
    gemPrice: HERO_PRICE,
  },
  {
    kind: 'hero',
    id: 'skadi',
    name: 'سكادي',
    title: 'سهم الجبال',
    role: 'assassin',
    maxHp: 96,
    levelImages: [
      'assets/starting-portraits/skadi.png',
      'assets/skadi-complete-pack/skadi-level-2.png',
      'assets/skadi-complete-pack/skadi-level-3.png',
      'assets/skadi-complete-pack/skadi-level-4.png',
      'assets/skadi-complete-pack/skadi-level-5.png',
    ],
    abilityIds: ['S1', 'S2', 'S3', 'S4'],
    story: STORIES.skadi,
    flavor:
      'قوس وسهم جليدي وتعقب دقيق. ضربة مركزة وإعداد للصيد؛ تأثير الجليد يخفض قوة الهجوم التالي ولا يلغي حركة للزعيم.',
    starter: true,
    gemPrice: HERO_PRICE,
  },
  {
    kind: 'hero',
    id: 'eir',
    name: 'إير',
    title: 'يد الشتاء الدافئة',
    role: 'healer',
    maxHp: 110,
    levelImages: [
      'assets/starting-portraits/eir.png',
      'assets/eir-complete-pack/eir-level-2.png',
      'assets/eir-complete-pack/eir-level-3.png',
      'assets/eir-complete-pack/eir-level-4.png',
      'assets/eir-complete-pack/eir-level-5.png',
    ],
    abilityIds: ['E1', 'E2', 'E3', 'E4'],
    story: STORIES.eir,
    flavor:
      'يد مضيئة وأعشاب وقوارير، وقصة إنقاذ المصابين من السم. عدم علاج نفسها قيد توازن مقصود: على الفريق أن يحمي من تنقذه.',
    starter: true,
    gemPrice: HERO_PRICE,
  },
  {
    kind: 'hero',
    id: 'zhuge',
    name: 'تشوغه ليانغ',
    title: 'سيد التشكيلات',
    role: 'support',
    maxHp: 92,
    levelImages: [
      'assets/starting-portraits/zhuge.png',
      'assets/zhuge-complete-pack/zhuge-level-2.png',
      'assets/zhuge-complete-pack/zhuge-level-3.png',
      'assets/zhuge-complete-pack/zhuge-level-4.png',
      'assets/zhuge-complete-pack/zhuge-level-5.png',
    ],
    abilityIds: ['Z1', 'Z2', 'Z3', 'Z4'],
    story: STORIES.zhuge,
    flavor:
      'مروحة ريش وخريطة مضيئة وقصة خطط مترابطة. يجهز ضربات الآخرين ويضعف هجوم العدو؛ لا يغير الأماكن الثابتة ولا يمنح حركات إضافية.',
    starter: true,
    gemPrice: HERO_PRICE,
  },
];

export const HERO_ABILITIES: AbilityDef[] = [
  // ——— هاياتو ———
  {
    id: 'H1',
    ownerId: 'hayato',
    name: 'وقفة البوابة',
    cost: 1,
    heroTarget: 'none',
    effects: [
      { type: 'damage', target: 'boss', amount: 8 },
      { type: 'shield', target: 'owner', amount: 8 },
    ],
    targetText: 'الزعيم للضرر، وهاياتو للصدّ.',
    displayText: 'اضرب الزعيم بـ8، واكتسب صدّ 8 لنفسك في الحركة نفسها.',
    note: 'دفاع صغير ملازم لضربة؛ لا يحمي بقية الفريق.',
    vfxText: 'أثر كاتانا نحو الزعيم، وإطار صدّ على هاياتو في نفس الحركة.',
    vfx: ['slash', 'shield'],
    image: 'assets/hayato-complete-pack/hayato-H1.png',
  },
  {
    id: 'H2',
    ownerId: 'hayato',
    name: 'درع الرفيق',
    cost: 2,
    heroTarget: 'ally-any',
    effects: [{ type: 'shield', target: 'chosen', amount: 22 }],
    targetText: 'بطل حي يختاره اللاعب، ويجوز هاياتو.',
    displayText: 'امنح حليفًا واحدًا، أو نفسك، صدّ 22.',
    note: 'رد فعال على ضربة واحدة معروفة؛ يضيع فائض الصدّ بعد الضربة.',
    vfxText: 'حلقة درع واحدة حول الهدف المختار مع القيمة22.',
    vfx: ['shield'],
    image: 'assets/hayato-complete-pack/hayato-H2.png',
  },
  {
    id: 'H3',
    ownerId: 'hayato',
    name: 'كاتانا الحارس',
    cost: 3,
    heroTarget: 'ally-any',
    effects: [
      { type: 'damage', target: 'boss', amount: 10 },
      { type: 'shield', target: 'chosen', amount: 28 },
    ],
    targetText: 'الزعيم للضرر، وبطل حي مختار للصدّ ويجوز هاياتو.',
    displayText: 'اضرب الزعيم بـ10، وامنح حليفًا واحدًا، أو نفسك، صدّ 28 في الحركة نفسها.',
    note: 'مكونا الهجوم والحماية مستقلان: سقوط الحليف المحدد يلغي حمايته فقط.',
    vfxText: 'أثر كاتانا نحو الزعيم وإطار حماية28 حول الحليف المختار؛ يعرض كل جزء إذا كان صالحًا.',
    vfx: ['slash', 'shield'],
    image: 'assets/hayato-complete-pack/hayato-H3.png',
  },
  {
    id: 'H4',
    ownerId: 'hayato',
    name: 'بوابة للجميع',
    cost: 4,
    heroTarget: 'none',
    effects: [{ type: 'shield', target: 'allHeroes', amount: 14 }],
    targetText: 'كل الأبطال الأحياء بمن فيهم هاياتو.',
    displayText: 'امنح كل بطل حي، بمن فيهم هاياتو، صدّ 14.',
    note: 'حتى 70 حماية موزعة؛ ضد ضربة منفردة لن تستفيد من معظمها.',
    vfxText: 'نبضة دفاع تتفرع لكل بطل حي مع صدّ14 لكل واحد.',
    vfx: ['shield'],
    image: 'assets/hayato-complete-pack/hayato-H4.png',
  },
  // ——— نوبا ———
  {
    id: 'N1',
    ownerId: 'nuba',
    name: 'جمرة الكف',
    cost: 1,
    heroTarget: 'none',
    effects: [
      { type: 'damage', target: 'boss', amount: 6 },
      { type: 'dot', target: 'boss', status: 'burn', amount: 4, ticks: 2 },
    ],
    targetText: 'الزعيم.',
    displayText: 'اضرب الزعيم بـ6، ثم ضع عليه احتراق 4 × نهايتَي جولتين.',
    note: 'حتى 14 ضررًا منفردًا إن اكتمل الاحتراق؛ لا يتراكم مع احتراق آخر.',
    vfxText: 'جمرة تنتقل للزعيم، ووميض إصابة ثم رمز احتراق واضح.',
    vfx: ['fire'],
    image: 'assets/nuba-complete-pack-gallery/nuba-N1.png',
  },
  {
    id: 'N2',
    ownerId: 'nuba',
    name: 'تبديد الحجاب',
    cost: 2,
    heroTarget: 'none',
    effects: [
      { type: 'removeBarrier', target: 'boss' },
      { type: 'damage', target: 'boss', amount: 14 },
    ],
    targetText: 'الزعيم.',
    displayText: 'أزل صدّ الزعيم وانعكاسه أولًا، ثم اضربه بـ14.',
    note: 'يزيل حتى الحاجز الذي أنشأه الزعيم في الحركة نفسها.',
    vfxText: 'تلاشي حاجز الزعيم وانعكاسه إن وُجدا، ثم ومضة نار للضربة14.',
    vfx: ['barrier-break', 'fire'],
    image: 'assets/nuba-complete-pack-gallery/nuba-N2.png',
  },
  {
    id: 'N3',
    ownerId: 'nuba',
    name: 'قبضة القيظ',
    cost: 3,
    heroTarget: 'none',
    effects: [
      { type: 'damage', target: 'boss', amount: 24 },
      { type: 'dot', target: 'boss', status: 'burn', amount: 4, ticks: 2 },
    ],
    targetText: 'الزعيم.',
    displayText: 'اضرب الزعيم بـ24، ثم ضع عليه احتراق 4 × نهايتَي جولتين.',
    note: 'حتى 32 ضررًا منفردًا؛ استعماله فوق احتراق موجود يجدد المدة فقط.',
    vfxText: 'موجة نار قصيرة نحو الزعيم ثم رمز احتراق جديد أو متجدد.',
    vfx: ['fire'],
    image: 'assets/nuba-complete-pack-gallery/nuba-N3.png',
  },
  {
    id: 'N4',
    ownerId: 'nuba',
    name: 'شمس بين الكفين',
    cost: 4,
    heroTarget: 'none',
    effects: [
      {
        type: 'damage',
        target: 'boss',
        amount: 36,
        bonus: { kind: 'ifBossBurning', amount: 12, consumeBurn: true },
      },
    ],
    targetText: 'الزعيم.',
    displayText: 'اضرب الزعيم بـ36. إذا كان محترقًا، استهلك الاحتراق وأضف 12 إلى الضربة.',
    note: '48 كحد أساسي مشروط؛ استهلاك الاحتراق يلغي نبضاته المتبقية.',
    vfxText:
      'وهج شمسي قصير؛ إذا استُهلك الاحتراق ينطفئ رمزه مع إشارة المكافأة12، وإلا اعرض الضربة الأساسية فقط.',
    vfx: ['sun'],
    image: 'assets/nuba-complete-pack-gallery/nuba-N4.png',
  },
  // ——— سكادي ———
  {
    id: 'S1',
    ownerId: 'skadi',
    name: 'أثر في الثلج',
    cost: 1,
    heroTarget: 'none',
    effects: [
      { type: 'damage', target: 'boss', amount: 6 },
      { type: 'huntMark', target: 'boss', amount: 10 },
    ],
    targetText: 'الزعيم.',
    displayText: 'اضرب الزعيم بـ6، ثم ضع علامة صيد: +10 للضربة المباشرة التالية من فريقك.',
    note: 'العلامة لا تقوي هذا السهم نفسه؛ أي مهاجم قد يستهلكها قبل سكادي.',
    vfxText: 'سهم صغير ثم علامة صيد على الزعيم بعد الإصابة.',
    vfx: ['arrow', 'mark'],
    image: 'assets/skadi-complete-pack/skadi-S1.png',
  },
  {
    id: 'S2',
    ownerId: 'skadi',
    name: 'سهم بين الصفائح',
    cost: 2,
    heroTarget: 'none',
    effects: [{ type: 'damage', target: 'boss', amount: 20, piercing: true }],
    targetText: 'الزعيم.',
    displayText: 'اضرب الزعيم بـ20 متجاوزًا الصدّ. اترك الصدّ في مكانه.',
    note: 'يتجاوز المرآة بلا انعكاس؛ الحاجز يظل خطرًا على المهاجم التالي.',
    vfxText: 'سهم ثاقب يمر عبر الحاجز دون كسره أو تشغيل انعكاسه.',
    vfx: ['arrow-pierce'],
    image: 'assets/skadi-complete-pack/skadi-S2.png',
  },
  {
    id: 'S3',
    ownerId: 'skadi',
    name: 'وتر الصقيع',
    cost: 3,
    heroTarget: 'none',
    effects: [
      { type: 'damage', target: 'boss', amount: 26 },
      { type: 'weaken', target: 'boss', amount: 6 },
    ],
    targetText: 'الزعيم.',
    displayText: 'اضرب الزعيم بـ26، ثم أضعف هجومه المباشر التالي بـ6 لكل هدف.',
    note: 'التبريد يبدأ بعد الحركة؛ لا يخفف الضربة المتزامنة ولا يحذف حركة.',
    vfxText: 'سهم بوميض بارد، ثم أيقونة إضعاف الهجوم التالي؛ لا تجميد يحذف حركة.',
    vfx: ['arrow', 'debuff'],
    image: 'assets/skadi-complete-pack/skadi-S3.png',
  },
  {
    id: 'S4',
    ownerId: 'skadi',
    name: 'نهاية المطاردة',
    cost: 4,
    heroTarget: 'none',
    effects: [{ type: 'damage', target: 'boss', amount: 34, markBonusOverride: 18 }],
    targetText: 'الزعيم.',
    displayText: 'اضرب الزعيم بـ34. إذا حمل علامة صيد، استهلكها مقابل +18 بدل +10.',
    note: '52 قبل أي تقوية أخرى؛ لا تجمع 18 و10 للعلامة نفسها.',
    vfxText: 'سهم قوي؛ عند وجود العلامة تُستهلك وتظهر المكافأة18 بدل10.',
    vfx: ['arrow'],
    image: 'assets/skadi-complete-pack/skadi-S4.png',
  },
  // ——— إير ———
  {
    id: 'E1',
    ownerId: 'eir',
    name: 'ضماد المرفأ',
    cost: 1,
    heroTarget: 'ally-other',
    effects: [{ type: 'heal', target: 'chosen', amount: 16 }],
    targetText: 'حليف آخر حي مختار؛ ممنوع إير.',
    displayText: 'أعد 16 حياة لحليف آخر حي.',
    note: 'إير لا تستهدف نفسها. يصلح لإنقاذ حليف في نفس حركة إصابته.',
    vfxText: 'توهج علاج صغير على الحليف الآخر فقط.',
    vfx: ['heal'],
    image: 'assets/eir-complete-pack/eir-E1.png',
  },
  {
    id: 'E2',
    ownerId: 'eir',
    name: 'جرعة مضادة للسم',
    cost: 2,
    heroTarget: 'ally-other',
    effects: [
      { type: 'heal', target: 'chosen', amount: 20 },
      { type: 'cleanse', target: 'chosen', remove: ['poison', 'bleed', 'weaken'] },
    ],
    targetText: 'حليف آخر حي مختار؛ ممنوع إير.',
    displayText: 'أعد 20 حياة لحليف آخر حي، وأزل سمه ونزيفه وإضعاف هجومه القديم.',
    note: 'لا يمسح سمًا جديدًا يطبقه الزعيم بعد الضربة المتزامنة.',
    vfxText:
      'توهج علاج وإزالة أيقونات السم والنزيف والإضعاف القديم من الحليف الآخر؛ ظهور حالة جديدة لاحقًا يبقى ممكنًا.',
    vfx: ['heal', 'cleanse'],
    image: 'assets/eir-complete-pack/eir-E2.png',
  },
  {
    id: 'E3',
    ownerId: 'eir',
    name: 'يد الشتاء الدافئة',
    cost: 3,
    heroTarget: 'ally-other',
    effects: [{ type: 'heal', target: 'chosen', amount: 38 }],
    targetText: 'حليف آخر حي مختار؛ ممنوع إير.',
    displayText: 'أعد 38 حياة لحليف آخر حي.',
    note: 'قوي ضد الإصابة المركزة؛ أي مقدار يتجاوز الحياة القصوى يضيع.',
    vfxText: 'توهج علاج أوضح على الحليف الآخر فقط.',
    vfx: ['heal'],
    image: 'assets/eir-complete-pack/eir-E3.png',
  },
  {
    id: 'E4',
    ownerId: 'eir',
    name: 'مصابيح النجاة',
    cost: 4,
    heroTarget: 'none',
    effects: [{ type: 'heal', target: 'otherHeroes', amount: 20 }],
    targetText: 'كل الحلفاء الآخرين الأحياء؛ ممنوع إير.',
    displayText: 'أعد 20 حياة لكل الحلفاء الآخرين الأحياء. لا يشمل إير.',
    note: 'حتى 80 علاجًا عند وجود أربعة رفاق؛ مردوده ينقص بسقوطهم.',
    vfxText: 'نبضة علاج متزامنة على الرفاق الأحياء باستثناء إير.',
    vfx: ['heal'],
    image: 'assets/eir-complete-pack/eir-E4.png',
  },
  // ——— تشوغه ليانغ ———
  {
    id: 'Z1',
    ownerId: 'zhuge',
    name: 'قراءة النية',
    cost: 1,
    heroTarget: 'none',
    effects: [{ type: 'weaken', target: 'boss', amount: 6 }],
    targetText: 'الزعيم.',
    displayText: 'أضعف الهجوم المباشر التالي للزعيم بـ6 لكل هدف. يبدأ بعد هذه الحركة.',
    note: 'قد يمنع 30 ضررًا إذا جاء هجوم على خمسة؛ وقد يمنع 6 فقط ضد هدف واحد.',
    vfxText: 'رمز إضعاف على الزعيم يظهر بعد الحركة.',
    vfx: ['debuff'],
    image: 'assets/zhuge-complete-pack/zhuge-Z1.png',
  },
  {
    id: 'Z2',
    ownerId: 'zhuge',
    name: 'إشارة المروحة',
    cost: 2,
    heroTarget: 'ally-any',
    effects: [
      { type: 'shield', target: 'chosen', amount: 8 },
      { type: 'focus', target: 'chosen', amount: 14 },
    ],
    targetText: 'بطل حي مختار، ويجوز تشوغه.',
    displayText: 'امنح حليفًا واحدًا، أو نفسك، صدّ 8 فورًا؛ وبعد الحركة، تركيز +14 لضربته المباشرة التالية.',
    note: 'الحماية فورية، والتقوية مؤجلة؛ وضع التركيز على بطل لا يهاجم يهدره.',
    vfxText: 'إطار صدّ8 فوري على المختار، ثم رمز تركيز14 بعد الحركة.',
    vfx: ['shield', 'buff'],
    image: 'assets/zhuge-complete-pack/zhuge-Z2.png',
  },
  {
    id: 'Z3',
    ownerId: 'zhuge',
    name: 'كشف الثغرة',
    cost: 3,
    heroTarget: 'none',
    effects: [{ type: 'expose', target: 'boss', amount: 16, charges: 2 }],
    targetText: 'الزعيم؛ استفادة الضربتين التاليتين من الفريق.',
    displayText: 'بعد الحركة، تصبح الضربتان المباشرتان التاليتان من فريقك ضد الزعيم أقوى بـ16 لكل ضربة.',
    note: 'حتى +32 إذا لحقت ضربتان قبل انتهاء الأثر؛ لا يسبب ضررًا وحده.',
    vfxText: 'علامة كشف على الزعيم بشحنتين واضحتين؛ لا رقم ضرر عند إنشائها.',
    vfx: ['expose'],
    image: 'assets/zhuge-complete-pack/zhuge-Z3.png',
  },
  {
    id: 'Z4',
    ownerId: 'zhuge',
    name: 'خطة النجاة والهجوم',
    cost: 4,
    heroTarget: 'none',
    effects: [
      { type: 'focus', target: 'allHeroes', amount: 12 },
      { type: 'weaken', target: 'boss', amount: 8 },
    ],
    targetText: 'كل الأبطال الأحياء للتركيز، والزعيم للإضعاف.',
    displayText: 'بعد الحركة، امنح كل بطل حي تركيز +12، وأضعف هجوم الزعيم المباشر التالي بـ8 لكل هدف.',
    note: 'في هذا الفريق، ثلاثة أبطال فقط يملكون هجمات: حتى +36 ضررًا و40 تخفيفًا مشروطين.',
    vfxText: 'رموز تركيز12 على الأبطال الأحياء وإضعاف8 على الزعيم بعد الحركة.',
    vfx: ['buff', 'debuff'],
    image: 'assets/zhuge-complete-pack/zhuge-Z4.png',
  },
];
